Cleanup
Max-Noren/Blue pull request #21
Opened 2021-10-17 18:23 UTC by Max-Noren

Felicia has cleaned the code of comments and redundant code

Co-Authored-By: dex2503 <73958448+dex2503@users.noreply.github.com>

2021-10-17 20:01 UTC, Snarkjakten requested changes
Det är ett par kommentarer om manuella tester kvar i koden som kan tas bort
(index.php rad 8 och 11)

Och ett litet typo när vi ändå håller på: outputing borde vara outputting
(display.php rad 3)

2021-10-17 20:18 UTC, gaddan approved these changes

2021-10-18 07:59 UTC, lisaloving approved these changes

2021-10-18 08:07 UTC, Yoschu approved these changes

2021-10-18 08:12 UTC, felixbrunnegard approved these changes

2021-10-18 08:20 UTC, Max-Noren reviewed
Add File descriptions to traveling.php and FunctionTest.php

2021-10-18 08:32 UTC, merged