Update index.php
Max-Noren/Blue pull request #5
Opened 2021-09-28 12:27 UTC by dex2503

Co2 equivalence displayed in form of cheese sandwiches, etc.

Co-Authored-By: lisaloving <78026882+lisaloving@users.noreply.github.com>

2021-09-28 12:41 UTC, lisaloving approved these changes

2021-09-28 12:59 UTC, Max-Noren approved these changes

2021-09-28 13:02 UTC, jopers approved these changes

2021-09-28 13:34 UTC, Max-Noren approved these changes

2021-09-28 13:47 UTC, lisaloving commented
(helt otestad) METOD SOM ISTÄLLET TAR IN CO2, SEN GÖR OUTPUT ARRAY MED array[0]=antal plastpåsar osv.
#____________________
# This function displays the CO2 equivalence in cheese sandwiches, plastic bags and tumble drying sessions for the trip.
# The function takes in CO2 (regardless of trip or transportationmode) and returns an array with the equvalent number
# of plastic bags, cheese sandwitches and tumbledryer sessions.
#____________________
 function carbonEquivalent($CO2)
 {
    //how many grams of CO2 is (approx) the emissions from a cheese sandwitch (ostMacka), plasticbag and dryer 
    $ostMacka = 345;
    $plasticbag = 33;
    $dryer = 1074;
    //calculates the nr of each that represents the given CO2 emissions
    $eqvivalentOstMacka = number_format($CO2 / $ostMacka, 1);
    $eqvivalentPlasticbag = number_format($CO2 / $plasticbag, 1);
    $eqvivalentDryer = number_format($CO2 / $dryer, 1);
    //return the equivalent numbers of items in this order: plastic bags, cheese sandwitch, nr of tumble drying sessions
	$lessThanThisIsBasicallyZero = 15;
    if($CO2 < $lessThanThisIsBasicallyZero){
	return array("zero", "zero", "zero");
    }else{
    	return array($eqvivalentPlasticbag, $eqvivalentOstMacka,  $eqvivalentDryer);
    }
 }

2021-09-29 14:33 UTC, Snarkjakten requested changes
1) Jag vill föreslå att vi inte blandar svenska och engelska variabelnamn (ostMacka kan bytas till cheeseSandwich t ex)

2) eqvivalentOstMacka, eqvivalentPlasticBag och eqvivalentDryer har typos som borde fixas (eqvivalent -> equivalent)

2021-09-30 12:25 UTC, closed without merging